#!/usr/bin/env python3
"""One-time, reproducible asset export for the Lothar-Check board.

Outputs:
  assets/background.png         board backdrop (PSD, Flags + Countries hidden)
  assets/flags/<id>.png         48 flag images (square, downloaded)
  assets/fonts/*.otf            Gotham fonts (copied)
  assets/teams.json             team data (reference + tests)
  src/generated/teams.ts        team data (bundled into app.js)

Requires: psd_tools, Pillow (both already installed). Network needed ONLY here.
"""
import json
import os
import shutil
import urllib.request
from psd_tools import PSDImage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PSD_PATH = os.path.join(ROOT, "Lothar_Flags_v03.psd")
FONT_SRC = "/Users/iasi/Documents/Gotham 3.202"
ASSETS = os.path.join(ROOT, "assets")
FLAGS = os.path.join(ASSETS, "flags")
FONTS = os.path.join(ASSETS, "fonts")
GEN = os.path.join(ROOT, "src", "generated")

# (German name, id, FIFA code). id == iso2 except England/Scotland.
TEAMS = [
    ("Argentinien", "ar", "ARG"), ("Australien", "au", "AUS"), ("Ägypten", "eg", "EGY"),
    ("Algerien", "dz", "ALG"), ("Belgien", "be", "BEL"), ("Bosnien und Herzegowina", "ba", "BIH"),
    ("Brasilien", "br", "BRA"), ("Curaçao", "cw", "CUW"), ("Deutschland", "de", "GER"),
    ("DR Kongo", "cd", "COD"), ("Ecuador", "ec", "ECU"), ("Elfenbeinküste", "ci", "CIV"),
    ("England", "gb-eng", "ENG"), ("Frankreich", "fr", "FRA"), ("Ghana", "gh", "GHA"),
    ("Haiti", "ht", "HAI"), ("Irak", "iq", "IRQ"), ("Iran", "ir", "IRN"),
    ("Japan", "jp", "JPN"), ("Jordanien", "jo", "JOR"), ("Kanada", "ca", "CAN"),
    ("Kap Verde", "cv", "CPV"), ("Katar", "qa", "QAT"), ("Kolumbien", "co", "COL"),
    ("Kroatien", "hr", "CRO"), ("Marokko", "ma", "MAR"), ("Mexiko", "mx", "MEX"),
    ("Neuseeland", "nz", "NZL"), ("Niederlande", "nl", "NED"), ("Norwegen", "no", "NOR"),
    ("Österreich", "at", "AUT"), ("Panama", "pa", "PAN"), ("Paraguay", "py", "PAR"),
    ("Portugal", "pt", "POR"), ("Saudi-Arabien", "sa", "KSA"), ("Schottland", "gb-sct", "SCO"),
    ("Schweden", "se", "SWE"), ("Schweiz", "ch", "SUI"), ("Senegal", "sn", "SEN"),
    ("Spanien", "es", "ESP"), ("Südafrika", "za", "RSA"), ("Südkorea", "kr", "KOR"),
    ("Tschechien", "cz", "CZE"), ("Tunesien", "tn", "TUN"), ("Türkei", "tr", "TUR"),
    ("Uruguay", "uy", "URU"), ("USA", "us", "USA"), ("Usbekistan", "uz", "UZB"),
]

# IDs not on the insyde country endpoint -> flagcdn fallback.
FLAGCDN = {"gb-eng": "gb-eng", "gb-sct": "gb-sct"}


def export_background():
    psd = PSDImage.open(PSD_PATH)
    for layer in psd:
        if layer.name in ("Flags", "Countries"):
            layer.visible = False
    img = psd.composite(force=True)
    img.convert("RGB").save(os.path.join(ASSETS, "background.png"))
    print("background.png", img.size)


def download(url, dest):
    req = urllib.request.Request(url, headers={"User-Agent": "lothar-export"})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    with open(dest, "wb") as f:
        f.write(data)


def export_flags():
    os.makedirs(FLAGS, exist_ok=True)
    for de, tid, code in TEAMS:
        dest = os.path.join(FLAGS, f"{tid}.png")
        if tid in FLAGCDN:
            url = f"https://flagcdn.com/w160/{FLAGCDN[tid]}.png"
        else:
            url = f"https://flags.api.insyde.one/img/c/{tid}/square/h160.png"
        try:
            download(url, dest)
            print("flag", tid, "OK")
        except Exception as e:
            print("flag", tid, "FAILED", url, e)
            raise


def export_fonts():
    os.makedirs(FONTS, exist_ok=True)
    for name in os.listdir(FONT_SRC):
        if name.lower().endswith(".otf"):
            shutil.copy(os.path.join(FONT_SRC, name), os.path.join(FONTS, name))
    print("fonts copied")


def write_team_data():
    os.makedirs(GEN, exist_ok=True)
    records = [
        {"id": tid, "de": de, "code": code, "iso2": tid, "flagFile": f"assets/flags/{tid}.png"}
        for de, tid, code in TEAMS
    ]
    with open(os.path.join(ASSETS, "teams.json"), "w", encoding="utf-8") as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
    ts = (
        "// AUTO-GENERATED by scripts/export_assets.py — do not edit by hand.\n"
        "import { Team } from '../types';\n\n"
        "export const TEAMS: Team[] = " + json.dumps(records, ensure_ascii=False, indent=2) + ";\n"
    )
    with open(os.path.join(GEN, "teams.ts"), "w", encoding="utf-8") as f:
        f.write(ts)
    print("teams data:", len(records), "teams")


if __name__ == "__main__":
    os.makedirs(ASSETS, exist_ok=True)
    export_background()
    export_flags()
    export_fonts()
    write_team_data()
    print("DONE")
